CREATE TABLE ASSISTS (
    CCustomerID INT NOT NULL,
    EEmployeeID INT NOT NULL,
    PRIMARY KEY (CCustomerID, EEmployeeID), 
    FOREIGN KEY (CCustomerID) REFERENCES CUSTOMER(CustomerID),
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EEmployeeID) REFERENCES EMPLOYEE(EmployeeID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
