CREATE TABLE CONTAINS (
    Quantity INT NOT NULL CHECK (Quantity > 0),
    Price DECIMAL(10, 2) NOT NULL CHECK (Price >= 0),
    OOrderID INT NOT NULL,
    BBookID INT NOT NULL,
    PRIMARY KEY (OOrderID, BBookID),
    FOREIGN KEY (OOrderID) REFERENCES ORDERS(OrderID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BBookID) REFERENCES BOOK(BookID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
