CREATE TABLE CONTAINS (
    Quantity INT,
    Price DECIMAL(10, 2),
    OOrderID INT,
    BBookID INT,
    PRIMARY KEY (OOrderID, BBookID),
    FOREIGN KEY (OOrderID) REFERENCES ORDERS(OrderID),
    FOREIGN KEY (BBookID) REFERENCES BOOK(BookID)
);
