CREATE TABLE EMPLOYEE (
    EmployeeID INT PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    HireDate DATE NOT NULL,
    Position VARCHAR(100) NOT NULL,
    Age INT NOT NULL CHECK (Age>=18)
);