CREATE TABLE MANAGES (
    IInventoryID INT,
    EEmployeeID INT,
    PRIMARY KEY (IInventoryID, EEmployeeID),
    FOREIGN KEY (IInventoryID) REFERENCES INVENTORY(InventoryID),
    FOREIGN KEY (EEmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);