CREATE TABLE MANAGES (
    IInventoryID INT NOT NULL,
    EEmployeeID INT NOT NULL,
    PRIMARY KEY (IInventoryID, EEmployeeID),
    FOREIGN KEY (IInventoryID) REFERENCES INVENTORY(InventoryID),
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EEmployeeID) REFERENCES EMPLOYEE(EmployeeID)
        ON DELETE CASCADE ON UPDATE CASCADE
);