CREATE TABLE PROCESSES (
    OOrderID INT NOT NULL,
    EEmployeeID INT NOT NULL,
    PRIMARY KEY (OOrderID, EEmployeeID),
    FOREIGN KEY (OOrderID) REFERENCES ORDERS(OrderID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EEmployeeID) REFERENCES EMPLOYEE(EmployeeID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
