CREATE TABLE WRITES (
    AAuthorID INT NOT NULL,
    BBookID INT NOT NULL,
    PRIMARY KEY (AAuthorID, BBookID), 
    FOREIGN KEY (AAuthorID) REFERENCES AUTHOR(AuthorID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BBookID) REFERENCES BOOK(BookID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
