CREATE TABLE WRITES (
    AAuthorID INT,
    BBookID INT,
    PRIMARY KEY (AAuthorID, BBookID), 
    FOREIGN KEY (AAuthorID) REFERENCES AUTHOR(AuthorID),
    FOREIGN KEY (BBookID) REFERENCES BOOK(BookID)
);
